// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.Team190Robot.Robot;
import org.usfirst.frc190.Team190Robot.subsystems.Shooter;

// TODO: Write Autonomous

/**
 *
 */
public class  AutonomousCommand extends Command {

    Shoot shootCmd = new Shoot();
    int shots = 0;
    
    public AutonomousCommand() {
        requires(Robot.shooter);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.shooter.enableWheels();
        shots = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.shooter.setPitch(Shooter.AUTONOMOUS_DISTANCE);
        Robot.shooter.setSpeed(Shooter.IDEAL_WHEEL_SPEED);
        if (Robot.shooter.isReadyToShoot() && !shootCmd.isRunning() && shots < 3)
        {
            shootCmd.start();
            shots++;
        }
        
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (shots == 3 && !shootCmd.isRunning());
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.shooter.disableWheels();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        Robot.shooter.disableWheels();
    }
}
