// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

// TODO: Handle the timeouts

/**
 *  We are currently hanging on the a rung by the MGA's.
 *  Everything else is stored, and the OSHA is pivoted backwards
 */
public class ClimbLevel extends CommandGroup {
    
    public  ClimbLevel() {
        OSHARetractInClimbing killRetract;
        
        //extend the OSHA
        /*addSequential(new OSHAExtend());
        //pivot forward
        addSequential(new OSHAPivotForward());
        //retract the OSHA
        addParallel(new OSHARetractInClimbing());
        //wait for user input
        addSequential(new WaitForSwing());
        //raise the MGAs
        addParallel(new MGAExtend());
        // Wait until the MGA's have latched onto the next level
        addSequential(new WaitForMGAs());
        // Stop the OSHA's in parallel with retracting the MGA
        //addParallel(new OSHAStop(killRetract));
        //retract the MGAs
        addSequential(new MGARetract());
        // Pivot the OSHA back for the next level
        addSequential(new OSHAPivotBack());
        /*
         * We now one level up from where we started
         * The MGA's are retracted, the OSHA is pivoted back and down,
         * and the rest of the subsystems are stored
         */
        
        
        //The MGAs are on the bar; let's retract them
        addParallel(new MGARetract());
        // Pivot the OSHA back for the next level
        addSequential(new OSHAPivotBack());
        //extend the OSHA
        addSequential(new OSHAExtend());
        //pivot forward
        addSequential(new OSHAPivotForward());    
        addParallel(new WaitAndExtend());
        //retract the OSHA
        addSequential(new OSHARetractInClimbing());
        // Wait until the MGA's have latched onto the next level
        //addSequential(new WaitForMGAs());
        // Stop the OSHA's in parallel with retracting the MGA
        //addParallel(new OSHAStop(killRetract));
        //retract the MGAs
        
        
        
        
    }
}
