// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *  We are currently hanging on the a rung by the MGA's.
 *  Everything else is stored, and the OSHA is pivoted backwards
 */
public class Level2 extends CommandGroup {
    
    public  Level2() {
        //extend our long arm
        addSequential(new OSHAExtend());
        //pivot forward
        addSequential(new OSHAPivotForward());
        //retract the OSHA
        // TODO: Make this parallel
        addSequential(new OSHARetract());
        //wait for user input
        // TODO: Change this to wait for gyro input
        addSequential(new WaitForNext());
        //raise the MGAs
        addSequential(new MGAExtend());
        // TODO: Wait for MGA input here
        // TODO: In parallel, stop the OSHA
        //retract the MGAs
        addSequential(new MGARetract());
        // TODO: Pivot OSHA
        //we now the the OSHA and MGAs on the second rung
        // TODO: Make this part of AutoClimb
        //climb to level three
        addSequential(new Level3());
        
    }
}
