// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc190.Team190Robot.Robot;

/**
 *
 */
public class Level1 extends CommandGroup {
    
    public  Level1() {
        //get into the ready state, if not already there
        addSequential(new ReadyForClimb());
        
        //extend the MGAs
        addSequential(new MGAExtend());
        //bumper bumpers engage
        
        //drive forward toward the bar
        addSequential(new DrivetoLevel1());
        //wait for user to press next
        addSequential(new WaitForNext());
        //pull up on the bar
        addSequential(new MGARetract());
        //wait for user to press next
        addSequential(new WaitForNext());
        //start the level two sequence
        addSequential(new Level2());
    }
}
