// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class Level2 extends CommandGroup {
    
    public  Level2() {
        //extend our long arm
        addSequential(new OSHAExtend());
        //pivot forward
        addSequential(new OSHAPivotForward());
        //retract the OSHA
        addSequential(new OSHARetract());
        //wait for user input
        addSequential(new WaitForNext());
        //raise the MGAs
        addSequential(new MGAExtend());
        //retract the MGAs
        addSequential(new MGARetract());
        //we now the the OSHA and MGAs on the second rung
        //wait for the user to hit next
        addSequential(new WaitForNext());
        //climb to level three
        addSequential(new Level3());
        
    }
}
