// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

// TODO: Remove this command

/**
 * At this point, the MGA's are on level 2, and the OSHA is a few inches
 * off the bar
 */
public class Level3 extends CommandGroup {
    
    public  Level3() {
        //angle the osha backwards
        addSequential(new OSHAPivotBack());
        //raise the osha up
        addSequential(new OSHAExtend());
        //pivot the OSHA towards the bar
        addSequential(new OSHAPivotForward());
        //retract the OSHA and pull the robot up off the second tier
        addSequential(new OSHARetract());
        //wait for the next button
        addSequential(new WaitForNext());
        addSequential(new MGAExtend());
        addSequential(new MGARetract());
        //we're now hanging on the third tier by the OSHA and MGAs
        //wait for the user to hit next
        addSequential(new WaitForNext());
        //WOMBO DAT COMBO
        addSequential(new WomboCombo());
        //disable all systems until game over
        addSequential(new WaitToWin());        
    }
}
