// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc190.Team190Robot.Robot;
import org.usfirst.frc190.Team190Robot.RobotMap;

/**
 *
 */
public class  OSHAExtend extends Command {

    public OSHAExtend() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        requires(Robot.oSHA);
        
        // TODO: Need to time this process, constanted
        this.setTimeout(20.0);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("Starting to extend the OSHAs");
        
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.oSHA.driveOSHA(Robot.oSHA.OSHAExtendSpeed, false);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (this.isTimedOut())
        {
            System.out.println("OSHA Extend exited with Timeout");
            return true;
        }
        if (Robot.oSHA.getUpperLimit())
        {
            System.out.println("OSHA Extend exited with Limit");
            return true;
        }
        /*if (!Robot.oSHA.isTensioned())
        {
            System.out.println("OSHA Extend exited with No Tension");
            return true;
        }*/
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
        
        Robot.oSHA.driveOSHA(0, false);
        if (isTimedOut())
            ClimbPyramid.Abort("the OSHA never hit the upper limit");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
