// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc190.Team190Robot.subsystems;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc190.Team190Robot.RobotMap;
import org.usfirst.frc190.Team190Robot.misc.ExtensiblePIDController;
import org.usfirst.frc190.Team190Robot.misc.GravityCompensationTerm;
import org.usfirst.frc190.Team190Robot.misc.VexEncoder;

/**
 *
 */
public class Dumper extends Subsystem {

    // Motors
    private SpeedController bucketMotor = new Victor(RobotMap.DUMPER_BUCKET_VICTOR);
    private SpeedController elbowMotor = new Victor(RobotMap.DUMPER_ELBOW_VICTOR);
    
    // Sensors
    public VexEncoder bucketEncoder = new VexEncoder(RobotMap.DUMPER_BUCKET_ENCODER);
    private AnalogChannel elbowPot = new AnalogChannel(RobotMap.DUMPER_ELBOW_POT);
    
    // PID Controllers
    public PIDController bucketPID = new PIDController(kP_BUCKET, kI_BUCKET, kD_BUCKET, bucketEncoder, bucketMotor);
    public ExtensiblePIDController elbowPID = new ExtensiblePIDController(kP_ELBOW, kI_ELBOW, kD_ELBOW, new PIDSource(){
        public double pidGet(){
            return elbowPot.getAverageVoltage();
        }
    }, elbowMotor);

    // PID Constants
    // TODO: Tune Constants
    private static final double kP_BUCKET = 3.0;
    private static final double kI_BUCKET = 0.020;
    private static final double kD_BUCKET = 0;
    private static final double kP_ELBOW = 1.5;
    private static final double kI_ELBOW = 0.01;
    private static final double kD_ELBOW = 0;
    private static final double kG_ELBOW = 0;
    private static final double T_ELBOW = 0;
    
    // Position Constants
    // top: 
    // bottom: 
    public final double FEEDER_SLOT_ELBOW = 1.98;
    public final double FEEDER_SLOT_WRIST = 0.0;
    public final double STORE_ELBOW = 0.5;
    public final double STORE_WRIST = 0.0;
    public final double CLEAR_ELBOW = 0.9;
    public final double CLEAR_WRIST = 0.0;
    public final double WOMBO_ELBOW = 3.64;
    public final double WOMBO_WRIST = -1.5;
    
    // we start off stored
    private boolean isStored = true;
    
    public Dumper(){
        
        // Set up PID Controllers
        bucketPID.setContinuous(false); 
        bucketPID.setAbsoluteTolerance(0.2); 
        bucketPID.setOutputRange(-1.0, 1.0);
        elbowPID.setContinuous(false); 
        elbowPID.setAbsoluteTolerance(0.2); 
        elbowPID.setOutputRange(-0.3, 0.8); 
        elbowPID.addTerm(new GravityCompensationTerm(kG_ELBOW, T_ELBOW));
       
        
        // Add components to the live window
        LiveWindow.addActuator("Dumper", "Bucket Motor", (Victor) bucketMotor);
        LiveWindow.addActuator("Dumper", "Bucket PID", bucketPID);
        try{
            LiveWindow.addSensor("Dumper", "Bucket Encoder", bucketEncoder);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
        LiveWindow.addActuator("Dumper", "Elbow Motor", (Victor) elbowMotor);
        LiveWindow.addSensor("Dumper", "Elbow Pot", elbowPot);
        LiveWindow.addActuator("Dumper", "Elbow PID", elbowPID);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // No default command
    }
    
    // TODO: Determine if this is enough to control the elbow and pivot, or if
    // we need more complex control to coordinate them
    
    /**
     * Sets the position of the pivot joint.  For the most part, use the 
     * constants defined in the class
     * @param pos The position to move to
     */
    public void setPivot(double pos){
        bucketPID.setSetpoint(pos);
    }
    
    /**
     * Sets the position of the elbow joint.  For the most part, use the
     * constants defined in the class
     * @param pos The position to set the elbow to
     */
    public void setElbow(double pos){
        elbowPID.setSetpoint(pos);
    }
    
    /**
     * Stops all movement of the subsystem
     */
    public void stopMovement(){
        bucketPID.setSetpoint(bucketEncoder.getPosition());
        elbowPID.setSetpoint(elbowPot.getAverageVoltage());
        bucketPID.disable();
        elbowPID.disable();
    }

    public void goClear(){
        isStored = false;
        //this.bucketPID.setSetpoint(CLEAR_WRIST);
        this.elbowPID.setSetpoint(CLEAR_ELBOW);
        //this.bucketPID.enable();
        this.elbowPID.enable();
    }
    public void goCollect(){
        isStored = false;
        this.bucketPID.setSetpoint(FEEDER_SLOT_WRIST);
        this.elbowPID.setSetpoint(FEEDER_SLOT_ELBOW);
        this.bucketPID.enable();
        this.elbowPID.enable();
    }
    public void goScore(){
        isStored = false;
        this.elbowPID.enable();
        this.elbowPID.setSetpoint(WOMBO_ELBOW);
        //wait to start the bucket moving
        Timer.delay(0.1);
        this.bucketPID.setSetpoint(WOMBO_WRIST);
        this.bucketPID.enable();
        
    }
    public void goStore(){
        isStored = true;
        this.bucketPID.setSetpoint(STORE_WRIST);
        this.elbowPID.setSetpoint(STORE_ELBOW);
        this.bucketPID.enable();
        this.elbowPID.enable();
    }
    public boolean isDone(){
        return this.bucketPID.onTarget() && this.elbowPID.onTarget();
    }
    public boolean isStored()
    {
        return isStored;
    }
    
    
}
