// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.subsystems;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc190.Team190Robot.RobotMap;
import org.usfirst.frc190.Team190Robot.commands.*;


/**
 *
 */
public class MGA extends Subsystem {
    
    // Actuators
    private Solenoid armSolenoid = new Solenoid(RobotMap.MGA_SOLENDOID);
    
    // Sensors
    private DigitalInput leftArmLimit = new DigitalInput(RobotMap.MGA_LEFT_LIMIT);
    private DigitalInput rightArmLimit = new DigitalInput(RobotMap.MGA_RIGHT_LIMIT);

    // TODO: Find the correct values for these
    // Constants for the MGA's positions
    public static final boolean MGA_UP = false;
    public static final boolean MGA_DOWN = true;
    
    public MGA(){
        // Add Components to LiveWindow
        LiveWindow.addActuator("MGA", "Arm Solenoid", armSolenoid);
        LiveWindow.addSensor("MGA", "Left Arm Limit", leftArmLimit);
        LiveWindow.addSensor("MGA", "Right Arm Limit", rightArmLimit);
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new MGADoNothing());
    }
    
    public void setPosition(boolean pos){
        armSolenoid.set(pos);
    }
}

