// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc190.Team190Robot.subsystems;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc190.Team190Robot.RobotMap;
import org.usfirst.frc190.Team190Robot.commands.*;


/**
 *
 */
public class OSHA extends Subsystem {
    
    // Actuatorss
    private Solenoid pivotSolenoid = new Solenoid(RobotMap.OSHA_PIVOT_SOLENOID);
    private Solenoid extensionSolenoid = new Solenoid(RobotMap.OSHA_EXTENSION_SOLENOID);
    private SpeedController winchVictor = new Victor(RobotMap.OSHA_WINCH_VICTOR);

    // Sensors
    private DigitalInput winchUpperLimit = new DigitalInput(RobotMap.OSHA_UPPER_LIMIT);
    private DigitalInput winchLowerLimit = new DigitalInput(RobotMap.OSHA_LOWER_LIMIT);
    private DigitalInput tensiometer = new DigitalInput(RobotMap.OSHA_TENSIOMETER);
    
    // OSHA Constants
    //TODO: Find the actual values to set the OSHA to
    public static final boolean OSHA_FORWARD = false;
    public static final boolean OSHA_BACKWARD = true;

    public OSHA(){
        // Put Components on Live Window
        LiveWindow.addActuator("OSHA", "Pivot Solenoid", pivotSolenoid);
        LiveWindow.addActuator("OSHA", "Winch Victor", (Victor) winchVictor);
        LiveWindow.addActuator("OSHA", "Extension Solenoid", extensionSolenoid);
        LiveWindow.addSensor("OSHA", "Winch Upper Limit", winchUpperLimit);
        LiveWindow.addSensor("OSHA", "Winch Lower Limit", winchLowerLimit);
        LiveWindow.addSensor("OSHA", "Tensiometer", tensiometer);
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new OSHADoNothing());
    }
    
    public void driveOSHA(int speed){
        
    }
    
    /**
     * Sets the position of the pivot.  Use the public position variables
     * in the class.
     * @param pos The position to set the OSHA to 
     */
    public void setPosition(boolean pos){
        pivotSolenoid.set(pos);
    }
}

